# Generated by Django 5.2.1 on 2025-05-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('room_type', models.CharField(choices=[('suite', 'Suite'), ('deluxe', 'Deluxe'), ('standard', 'Standard')], default='standard', max_length=20)),
                ('price_per_night', models.IntegerField(default=150)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('naira', 'Naira')], default='usd', max_length=10)),
                ('max_occupancy', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
